### ISSUE TITLE
Receive entity based on Entity ID

### ISSUE THREAD

**Issue by leander091** [PowervRNI/powervrni#12]
Hello,

I am trying to receive the name of an specific Entity within vRNI. But it looks like the Get-vRNIEntity cmdlet has no such parameter to receive an single object based on the entity_id. 

Do you know of an workaround to receive this information?

**Comment by smitmartijn** [comment]
Hi @leander091,

I believe you're looking for Get-vRNIEntityName?

PS /Users/msmit/VMware/Scripts/PowervRNI> Get-vRNIEntityName -EntityID 17603:1:834218005

entity_id         entity_type          time name
---------         -----------          ---- ----
17603:1:834218005 VirtualMachine 1573898313 3TA-LogicalRouter01-0

**Comment by leander091** [comment]
That was indeed the solution. :) I was not aware of that cmdlet, Thanks
