### ISSUE TITLE
Credential object in PowerShell 7.0.3 does not parse domain correctly

### ISSUE THREAD

**Issue by MallocArray** [PowervRNI/powervrni#19]
Using a Powershell Credential object with a username in the format username@domain.com is not parsed correctly to be added to the domain value part of the body and results in 'null' and an error that a domain is required.  Providing the same username format to the -username parameter works as expected.

$cred = Get-Credential -UserName 'username@domain.com'
Connect-vRNIServer -Server 'server.domain.com' -Credential $cred

DEBUG: Request: {
  "password": "password",
  "username": "username@domain.com",
  "domain": {
    "value": null,
    "domain_type": "LDAP"
  }
}
DEBUG: 2020-09-01T15:32:19  REST Call via Invoke-RestMethod: POST https://server.domain.com/api/ni/auth/token 
DEBUG: Headers: System.Collections.Hashtable
DEBUG: Body: {
  "password": "password",
  "username": "username@domain.com",
  "domain": {
    "value": null,
    "domain_type": "LDAP"
  }
}
WARNING: Invoke-vRNIRestMethod : Exception occured calling invoke-restmethod. Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Invoke-RestMethod: <redacted>\PowerShell\Modules\PowervRNI\1.8.131\PowervRNI.psm1:299:17
Line |
 299 |      $response = Invoke-RestMethod @invokeRestMethodParams
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":400,"message":"domain cannot be null!","details":[]}

#### This works as expected
Connect-vRNIServer -Server 'server.domain.com' -Username $cred.username

DEBUG: Request: {
  "password": "password",
  "username": "username@domain.com",
  "domain": {
    "value": "domain.com",
    "domain_type": "LDAP"
  }
}
DEBUG: 2020-09-01T15:35:19  REST Call via Invoke-RestMethod: POST https://server.domain.com/api/ni/auth/token 
DEBUG: Headers: System.Collections.Hashtable
DEBUG: Body: {
  "password": "password",
  "username": "username@domain.com",
  "domain": {
    "value": "domain.com",
    "domain_type": "LDAP"
  }
}

**Comment by alagoutte** [comment]
Hi,

What release do you are using ? because i think i get the same issue and fix on #16

**Comment by MallocArray** [comment]
Ah, I'm using 1.8.131 which is the latest version in the Powershell Gallery.  
If this is already fixed in 1.9, can it be published to the Gallery?

**Comment by smitmartijn** [comment]
Fixed with https://github.com/PowervRNI/powervrni/pull/16
