### ISSUE TITLE
Get-vRNIApplication only returns 10 applications

### ISSUE THREAD

**Issue by Jake3292** [PowervRNI/powervrni#2]
After running script to add application/tiers and debugging:

After 10 occurrences of for loop:
foreach($app in $application_list.results)
  {
    # Retrieve application details and store them
    $app_info = Invoke-vRNIRestMethod -Connection $Connection -Method GET -URI "/api/ni/groups/applications/$($app.entity_id)"
    $applications.Add($app_info) | Out-Null

    # Don't go on if we've already found the one the user wants specifically
    if($Name -eq $app_info.name) {
      break

Results in the following error:

Invoke-vRNIRestMethod : The API response received indicates a failure. 400 : Bad Request : Response Body: 
At C:\Program Files\WindowsPowerShell\Modules\PowervRNI\1.0.33\PowervRNI.psm1:220 char:7
+       throw $ErrorString
+       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invoke-vRNIRest...Response Body: :String) [], RuntimeException
    + FullyQualifiedErrorId : Invoke-vRNIRestMethod : The API response received indicates a failure. 400 : Bad Request : Response Body: 

###########################################
Looks like the results returned are paginated.

Recommend modifying this command  

$application_list = Invoke-vRNIRestMethod -Connection $Connection -Method GET -URI "/api/ni/groups/applications"

to 

$application_list = Invoke-vRNIRestMethod -Connection $Connection -Method GET -URI "/api/ni/groups/applications?size=500"

or working through the pagination.

**Comment by smitmartijn** [comment]
Thanks for the report; which version of vRNI are you using?

**Comment by Jake3292** [comment]
Latest -- 3.7.0.1519211678

**Comment by smitmartijn** [comment]
This has been fixed by @awickham10 's contribution.
