### ISSUE TITLE
Credential object in PowerShell 7.2.0 Preview.2 does not parse domain (@domain.com) correctly. Running 1.8.131

### ISSUE THREAD

**Issue by grimsrue** [PowervRNI/powervrni#20]
Having the same issue as MallocArray in #19. Domain is coming up "null" when entering username as username@domain.com under "Get-Credential". If I pass off the variable to -Username instead of -Credential it will work, but I have to type in the  password again.
I am running the PreRelease version of Powershell 7 (7.2.0 Preview.2)
I am running PowervRNI version 1.8.131 which is what is showing as the latest release on Github

PS C:\Users\eg2082> Connect-vRNIServer -Server vNETInsight.domain.com -Credential $cred -debug
DEBUG: Request: {
  "domain": {
    "value": null,
    "domain_type": "LDAP"
  },
  "username": "username@domain.com",
  "password": "Secret-password"
}
DEBUG: 2020-12-25T12:48:25  REST Call via Invoke-RestMethod: POST https:/vNETInsight.domain.com/log/api/ni/auth/token
DEBUG: Headers: System.Collections.Hashtable
DEBUG: Body: {
  "domain": {
    "value": null,
    "domain_type": "LDAP"
  },
  "username": "username@domain.com",
  "password": "Secret-password"
}
WARNING: Invoke-vRNIRestMethod : Exception occured calling invoke-restmethod. Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

**Comment by alagoutte** [comment]
Hi,

Do you have try to include the fix of #16 ? (there is not yet new release include this fix)

**Comment by grimsrue** [comment]
Hello Alagoutte,

I read the comments in #16, but I don't seem to seem to understand what the fix is or I am not reading the comments correctly.

**Comment by alagoutte** [comment]
it is a fix on PowerVRNI.psm1 file because there is wrong variable name (you can try to modified manually and need to import with -Force parameter)

**Comment by grimsrue** [comment]
Okay. I see it now. I was not seeing that there was a link to the screen shot of the powerVRNI.psm1 file modification. Thank for you help

**Comment by smitmartijn** [comment]
Fixed with https://github.com/PowervRNI/powervrni/pull/16
