### ISSUE TITLE
Requesting Expansion of filter usage for New-vRNIApplicationTier

### ISSUE THREAD

**Issue by grimsrue** [PowervRNI/powervrni#21]
Not sure if this is a place to request this or not.

I know that the PowervRNI cmdlets are still a work in process, but I would like to ask, when possible, if New-vRNIApplicationTier "-Filters" parameter could be expanded out a bit more to allow for other Filters types? Specifically "VM where Tag =" or "VM where Tag is not set", etc.

My environment is very large with many applications. We use vCenter Tags to help keep VMs organized. I know other SAs do something similar in other environments in other companies.

Thank you for the CMDlets. They are a big help.

**Comment by grimsrue** [comment]
Well.....I guess I should have spent a bit more time researching before posting a request for Application Tier membership filters.
It is not the CMDlets missing filters, but vRNI API Entity_Types having a limited number of filters.....which seems to be just 3 filters (IP Address, Security, Name). That seems to be ridiculous to me, but I it is what it is.

I guess we all have to wait for VMWare expand out their "VirtualMachine" or "BaseVirtualMachine" Entity_Type Filters in vRNI one day.

**Comment by smitmartijn** [comment]
Hi @grimsrue - indeed, the API needs more support, before PowervRNI can adopt it. I'm pushing hard internally. ;-)
