### ISSUE TITLE
issues with Get-vRNIDataSource using VRNI SAAS 

### ISSUE THREAD

**Issue by alladisrihari** [PowervRNI/powervrni#22]
Hi,

I am having issues while running Get-vRNIDataSource to pull the list of data sources from VRNI Cloud.
I am using powershell Core 7.1.2.
Other commands like get-vrnivcenter, get-vrnihost commands are working fine.
Line |
 299 |      $response = Invoke-RestMethod @invokeRestMethodParams
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":400,"message":"Data Source not available for current License","details":[]}

PSMessageDetails      : 
Exception             : Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Method: GET, RequestUri: 'https://api.mgmt.cloud.vmware.com/ni/api/ni/data-sources/velocloud', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
                        {
                          csp-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InNpZ25pbmdfMiJ9.eyJzdWIiOiIwY2VkMTA4Ny00NGVhLTQ2NTktOWRhYS03MzZiNTE3MDA1ZmQ6ZDkxMmMwMWItYTRkZi00OTQxLWFlMTAtMzBmY2RiZDMwYmViIiwiaXNzIjoiaHR0cHM6Ly9nYXouY3NwLXZpZG0tcHJvZC5jb20iLCJjb250ZXh0X25hbWUiOiI1MDYwNjMxMS1iNmJiLTRjM2YtYmMyMi0wNTUxNDg0Yzk4MjYiLCJhenAiOiJjc3BfcHJkX2dhel9pbnRlcm5hbF9jbGllbnRfaWQiLCJhdXRob3JpemF0aW9uX2RldGFpbHMiOltdLCJkb21haW4iOiJmaGxtYy5jb20iLCJjb250ZXh0IjoiZWUwM2E0OGUtYjM0Ny00Yjk4LTkyMGYtNTM1NDA3ODQ1MjVhIiwicGVybXMiOlsiY3NwOm9yZ19vd25lciIsImV4dGVybmFsL3liVWRvVEMwNWtZRkM5Wkc1NjBrcHNuMEk4TV8vdm1jLXVzZXI6cmVzdHJpY3RlZCIsImV4dGVybmFsLzlxam9OYWZEcDlYa3l5UUxjTENLV1BzQWlyMF8vdnJuaTphZG1pbiIsImV4dGVybmFsL3liVWRvVEMwNWtZRkM5Wkc1NjBrcHNuMEk4TV8vbnN4OmNsb3VkX2FkbWluIiwiZXh0ZXJuYWwvN2NKMm5nU19oUkNZX2JJYld1Y000S1dRd09vXy9sb2ctaW50ZWxsaWdlbmNlOmFkbWluIiwiZXh0ZXJuYWwvN3VOR3ZUYXRtR0FJU2NNbzNjUGhNd3Z1WlhZXy9oY3g6YWRtaW4iXSwiZXhwIjoxNjE3NDczMTAwLCJpYXQiOjE2MTc0NzEzMDAsImp0aSI6ImM0MzEzNGQzLTUxM2YtNDk2ZC05ZmU5LWRhMjQ2Y2Q4OGJjZCIsImFjY3QiOiJzcmloYXJpa3Jpc2huYV9hbGxhZGlAZnJlZGRpZW1hYy5jb20iLCJ1c2VybmFtZSI6ImYzNzA3MDMifQ.uQ2GM52NI_jPklyxHgjwrircP_McqhdDRmRVLU2DSRyjKJVXQV2U2BrpJ_qXDxynRWDZ1JoaPl_w5h3_tWYfGwu3V2MBlSzMz6QbVNCzFw0rmecwhW89mlIyDMmDuKawlGKacxhjh31uiBk2UGVVox54a41qArtn8U2OA5L7TF2Fpy9KfPP1AB2pHCyWZKbFe0savJhpq6wreYtG0v7p35Co1IolwjNlpoGcDps4pC9Blylwbz_PD0_wVU-VkZccKilIsUNL1iheHc-om_sWZ4rD7RGhp6qqZ3BliFIomCrR77USt-UaSAJ4J4n7cpTHZm1R04t6vImZikfzVZMcVQ
                          User-Agent: Mozilla/5.0
                          User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.18363; en-US)
                          User-Agent: PowerShell/7.1.2
                          Content-Type: application/json
                          Content-Length: 0
                        }
CategoryInfo          : InvalidOperation: (Method: GET, RequesΓÇªontent-Length: 0
                        }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : {"code":400,"message":"Data Source not available for current License","details":[]}
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-vRNIRestMethod, C:\OneDriveSync\OneDrive - Freddie Mac\Documents\PowerShell\Modules\PowervRNI\1.8.131\PowervRNI.psm1: line 299
                        at Get-vRNIDataSource<Process>, C:\OneDriveSync\OneDrive - Freddie Mac\Documents\PowerShell\Modules\PowervRNI\1.8.131\PowervRNI.psm1: line 773
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by smitmartijn** [comment]
Hi,

This is an issue with vRNI - the API returns it and PowervRNI only displays it. They're looking into it and fixing it soon.
