### ISSUE TITLE
Consistent 429 errors when application count is higher

### ISSUE THREAD

**Issue by Jake3292** [PowervRNI/powervrni#3]
When running with 57 applications consistently recieve 429 errors via API.

Recommend adding a sleep of 250 prior to invoking the RestMethod to avoid.  Not sure what the number of concurrent calls per token are for VRNI, so the number could be adjusted.  250 seems to function fine, 100/150 still received occasional 429's

    Start-Sleep -m 250
    $response = Invoke-RestMethod @invokeRestMethodParams

**Comment by smitmartijn** [comment]
The Get-vRNIApplication function didn't have any sleep, which is what @awickham10 added. I just pushed update https://github.com/PowervRNI/powervrni/commit/0d334b2ea06ed6bdbc973f0c9d5599c86e46aa98 which solves it in a more structured way so it also protects the user when using consecutive commands.

Tested this by creating 800 new applications with this oneliner:

`1..800 | % { New-vRNIApplication -Name Test-$_ }`

So I think this is pretty safe now.
