### ISSUE TITLE
vRNI Cloud does not support application fetch size of 2500

### ISSUE THREAD

**Issue by jamiegrandfield** [PowervRNI/powervrni#30]
When calling Get-vRNIApplication with no $Name specified, the fetch size of 2500 generates the following error on vRNI Cloud (API version currently 6.5 in our instance).

Code in question -
Line 2377 in PowervRNI.psm1 - `$listParams['Uri'] = '/api/ni/groups/applications/fetch?size=2500'`

Error -
`Invoke-RestMethod: {"code":400,"message":"Requested size: 2500 exceeds the supported limit: 100.","details":[]}`

Changing size to 100 works as expected.

**Comment by smitmartijn** [comment]
Thanks for the reminder, @jamiegrandfield ! I ran into this with a scheduled task, after vRNI Cloud was upgraded to 6.5. Unfortunately, it's a breaking change that was introduced in 6.5 and I'm working on getting the engineering team to make it *not* a breaking change, but in the mean time, I'll repackage PowervRNI with the fix this week. 😄

**Comment by smitmartijn** [comment]
Correction: it was introduced in 6.5.1. I've modified the API call in PowervRNI to use the max of 100 and published 6.51.185 to the powershellgallery: https://www.powershellgallery.com/packages/PowervRNI/6.51.185

**Comment by SharkyTheMishu** [comment]
Can we work around the 100 API limitation? I`m working in an environment where there is 1000+ apps and I can`t find a way to pull a full list.
