### ISSUE TITLE
Handling of ValueFromPipeline for Get-vRNIApplicationTier needs corrected

### ISSUE THREAD

**Issue by mtboren** [PowervRNI/powervrni#5]
Hello, @smitmartijn -

Firstly, thanks for the module -- great work so far!

In using the module, I see that `Get-vRNIApplicationTier` has an issue handling more than one `-Application` object from pipeline (it only acts on the last Application object received from the pipeline).

This is due to the function having no explicit `Process { }` scriptblock (and, so, the code in the function is treated as the `End { }` scriptblock).

We just need to add the `Process { }` scriptblock around the function's code, and all should be well. I'm working on a fork of your repo, and will add such a fix there.

Cheers,

Matt

**Comment by mtboren** [comment]
In addition to fixing this in a fork, I also added handling for accepting multiple Application object values for `-Application` parameter (like `Get-vRNIApplicationTier -Application (Get-vRNIApplication)`) -- this is standard PowerShell behavior (accepting multiple values for most parameters where it makes sense).

**Comment by smitmartijn** [comment]
Thank you, this is very useful. I think this also applies to a couple of other cmdlets (i.e. Enable-vRNIDataSource / Remove-vRNIDataSource, etc).

**Comment by mtboren** [comment]
Glad to try to help!

And, correct -- there are some other cmdlets in this same boat. I have now pushed commit https://github.com/mtboren/powervrni_fork/commit/95e2f3a3695bbbdd101c5d5d91b1124816b08c5e to a new branch in my fork that resolves that issue with those additional cmdlets.  I will make a PR soonish.

Have a good weekend
